### ISSUE TITLE
Object Cache Expiry Date is Minus Causing Error

### ISSUE THREAD

**Issue by iqbaljayadi** [jamesgol/woocommerce-cart-stock-reducer#65]
Hi,

I'm using Redis Object Cache with your plugin. The initial activation has no error, works fine when I'm doing the test, then in 3 or 4 hours the site crashed. Here's the error log:

`
2018/06/04 12:14:04 [error] 1314#0: *374109 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Predis\Response\ServerException: ERR invalid expire time in setex in /home/tonjoo/public_html/amilyhijab.com/wp-content/plugins/redis-cache/includes/predis/src/Client.php:370
Stack trace:
#0 /home/tonjoo/public_html/amilyhijab.com/wp-content/plugins/redis-cache/includes/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\StringSetExpire), Object(Predis\Response\Error))
#1 /home/tonjoo/public_html/amilyhijab.com/wp-content/plugins/redis-cache/includes/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\StringSetExpire))
#2 /home/tonjoo/public_html/amilyhijab.com/wp-content/object-cache.php(836): Predis\Client->__call('setex', Array)
#3 /home/tonjoo/public_html/amilyhijab.com/wp-content/object-cache.php(227): WP_Object_Cache->set('wc_cache_1_645b...', 'a:13:{s:4:"cart...', 'wc_session_id', -920)
#4 /home/tonjoo/public_html/amilyhijab.com/wp-content/plugins/woocommerce-cart-stock-reducer/includes/class-wc-csr-ses" while reading response header from upstream, client: 125.163.118.223, server: amilyhijab.com, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9270", host: "amilyhijab.com", referrer: "https://amilyhijab.com/wp-admin/edit.php?s=elis&post_status=all&post_type=shop_order&action=-1&m=0&_customer_user&paged=1&action2=-1"
`

In log, the cache expiry date is set to -920 which is invalid.

Perhaps you can help improving the compability with the redis cache? Thank you!

**Comment by jamesgol** [comment]
I've not had a chance to test with redis yet, I hopefully will at some point though.

To end up with a negative expiration time it must be trying to act on sessions that are already expired (or should have been expired).  I'll certainly need to dig into this more.

**Comment by jamesgol** [comment]
Finally getting a chance to test with redis.  Are you still using it?  Having any issues?  

Looking at the error above it would have been WooCommerce that set the expiration date
